# ============ APP DEPLOYMENT ============
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securing-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securing-web
  template:
    metadata:
      labels:
        app: securing-web
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-db 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: securing-web
        image: hant0505/dn-week8-app:146fab7d1fdd50c471fc65115245f40981ef127f
        imagePullPolicy: Always ##kodc never do argocd
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db:3306/week2"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Thu ha123"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQLDialect"
        livenessProbe:
          httpGet:
            path: /actuator/health # NÊN dùng health check
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          
          httpGet:
            path: /login
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health # NÊN dùng health check
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 5
          
          httpGet:
            path: /login
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

# ============ APP SERVICE ============
---
apiVersion: v1
kind: Service
metadata:
  name: securing-web-service
  labels:
    app: securing-web  # ⭐ Thêm label để ServiceMonitor match
spec:
  type: LoadBalancer
  selector:
    app: securing-web
  ports:
    - name: http  # ⭐ THÊM DÒNG NÀY
      port: 8085
      targetPort: 8085
      protocol: TCP
#12H05 3_11
# apiVersion: v1
# kind: Service
# metadata:
#   name: securing-web-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: securing-web
#   ports:
#     - port: 8085
#       targetPort: 8085
#       protocol: TCP