apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: week8
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hant0505/dn-week8.git'
    targetRevision: main
    path: gs-securing-web/initial/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
